import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased 
                   bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-900 
                   min-h-screen text-white`}
      >
        {/* Background Pattern */}
        <div className="fixed inset-0 bg-[url('/patterns/noise.png')] opacity-5 pointer-events-none" />
        <div className="fixed inset-0 bg-gradient-to-br from-transparent via-blue-500/5 to-purple-500/10 pointer-events-none" />
        
        <div className="relative z-10">
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
